import { Inter } from "next/font/google"
import { cookies } from "next/headers"

import { getTheme } from "./modules/getTheme"
import { Header } from "../components/organisms/Header"
import { COOKIE_KEY_THEME } from "../shared/constants/COOKIE_KEYS"

import type { FCWithChildren } from "../shared/types/FCWithChildren"
import type { Metadata } from "next"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
}

const RootLayout: FCWithChildren = (props) => {
  const { children } = props
  const theme = getTheme(cookies().get(COOKIE_KEY_THEME))

  return (
    <html data-theme={theme} lang="en">
      <body className={inter.className}>
        <Header themeFromServerCookie={theme} />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}

export default RootLayout
