import { Inter } from "next/font/google"
import { cookies } from "next/headers"

import { COOKIE_KEY_ESLINT_CONFIG, COOKIE_KEY_PACKAGE_MANAGER, COOKIE_KEY_THEME } from "@shared/constants/COOKIE_KEYS"

import { getEslintConfig } from "./modules/getEslintConfig"
import { getPackageManager } from "./modules/getPackageManager"
import { getTheme } from "./modules/getTheme"
import { MainContentProviders } from "../components/organisms/MainContentProviders"

import type { FCWithChildren } from "@shared/types/FCWithChildren"
import type { Metadata } from "next"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
}

const RootLayout: FCWithChildren = (props) => {
  const { children } = props
  const cookieObject = cookies()
  const theme = getTheme(cookieObject.get(COOKIE_KEY_THEME))
  const eslintConfig = getEslintConfig(cookieObject.get(COOKIE_KEY_ESLINT_CONFIG))
  const packageManager = getPackageManager(cookieObject.get(COOKIE_KEY_PACKAGE_MANAGER))

  return (
    <html data-theme={theme} lang="en">
      <body className={inter.className}>
        <MainContentProviders eslintConfig={eslintConfig} packageManager={packageManager}>
          {children}
        </MainContentProviders>
      </body>
    </html>
  )
}

export default RootLayout
